version: '3.9'
services:
  db:
    image: postgres:15.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: todo-checklist-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vaishu
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:


# command to create a new docker container
# docker run --name todo-checklist-app -e POSTGRES_PASSWORD=vaishu -p 5432:5432 -d postgres

# Connect pgAdmin to Dockerized PostgreSQL:
# Open pgAdmin on your local machine.

# In pgAdmin, right-click on "Servers" in the left sidebar and select "Create" > "Server...".

# In the "General" tab of the "Create - Server" dialog, enter a name for your server (e.g., "Docker PostgreSQL").

# Switch to the "Connection" tab:

# Host name/address: localhost
# Port: 5432
# Maintenance database: postgres
# Username: postgres
# Password: Enter the password you set when starting the PostgreSQL container.
# Click "Save" to add the server.

# You should now see your Docker PostgreSQL server listed under "Servers" in pgAdmin.